import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DOMParser,XMLSerializer} from '@xmldom/xmldom';
import JSZip from 'jszip';
import {inspectMission,readMission,exportMission,transformMission,changeHeight,changeSpeed,editWaypoint,editMappingTemplate,editAreaVertex,areaVertices,changeAreaTopology} from '../dji/mission';
Object.assign(globalThis,{DOMParser,XMLSerializer});
const prefix='<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:wpml="http://www.dji.com/wpmz/1.0.6"><Document>';
const config='<wpml:missionConfig><wpml:finishAction>goHome</wpml:finishAction><wpml:droneInfo><wpml:droneEnumValue>77</wpml:droneEnumValue></wpml:droneInfo><wpml:payloadInfo><wpml:payloadEnumValue>66</wpml:payloadEnumValue></wpml:payloadInfo><wpml:takeOffSecurityHeight>40</wpml:takeOffSecurityHeight><wpml:startPositionRef>48.1,11.5,40</wpml:startPositionRef></wpml:missionConfig>';
const template=prefix+config+'<Folder><wpml:templateType>mapping2d</wpml:templateType><wpml:templateId>0</wpml:templateId><wpml:autoFlightSpeed>2</wpml:autoFlightSpeed><wpml:waylineCoordinateSysParam><wpml:heightMode>relativeToStartPoint</wpml:heightMode><wpml:globalShootHeight>25</wpml:globalShootHeight></wpml:waylineCoordinateSysParam><Placemark><wpml:height>40</wpml:height><wpml:direction>355</wpml:direction><wpml:margin>0</wpml:margin><wpml:overlap><wpml:orthoCameraOverlapH>80</wpml:orthoCameraOverlapH><wpml:orthoCameraOverlapW>75</wpml:orthoCameraOverlapW></wpml:overlap><Polygon><outerBoundaryIs><LinearRing><coordinates>11.5,48.1,0 11.501,48.1,0 11.501,48.101,0 11.5,48.1,0</coordinates></LinearRing></outerBoundaryIs></Polygon></Placemark></Folder></Document></kml>';
function point(i:number){return `<Placemark><Point><coordinates>${11.5+i*.001},48.1,0</coordinates></Point><wpml:index>${i}</wpml:index><wpml:executeHeight>${40+i}</wpml:executeHeight><wpml:waypointSpeed>2</wpml:waypointSpeed><wpml:waypointHeadingAngle>170</wpml:waypointHeadingAngle><wpml:actionGroup><wpml:actionGroupId>${i}</wpml:actionGroupId><wpml:actionActuatorFunc>takePhoto</wpml:actionActuatorFunc><wpml:actionGroupStartIndex>${i}</wpml:actionGroupStartIndex></wpml:actionGroup><wpml:unknownDJIField>keep-me</wpml:unknownDJIField></Placemark>`;}
const waylines=prefix+config+'<Folder><wpml:templateId>0</wpml:templateId><wpml:waylineId>0</wpml:waylineId><wpml:executeHeightMode>relativeToStartPoint</wpml:executeHeightMode><wpml:distance>10</wpml:distance><wpml:duration>5</wpml:duration><wpml:autoFlightSpeed>2</wpml:autoFlightSpeed>'+point(0)+point(1)+'</Folder></Document></kml>';
const source=()=>inspectMission('synthetic.kmz',template,waylines,new Map([['wpmz/res/camera.bin',new Uint8Array([1,2,3])]]));
test('KMZ no-op round trip preserves raw DJI XML, resources, camera actions and namespace',async()=>{const m=source(),bytes=await exportMission(m),zip=await JSZip.loadAsync(bytes);assert.equal(await zip.file('wpmz/template.kml')!.async('string'),template);assert.equal(await zip.file('wpmz/waylines.wpml')!.async('string'),waylines);assert.deepEqual(await zip.file('wpmz/res/camera.bin')!.async('uint8array'),new Uint8Array([1,2,3]));const q=await readMission({name:'synthetic.kmz',arrayBuffer:async()=>bytes.slice().buffer as ArrayBuffer});assert.equal(q.points.length,2);assert.equal(q.templateType,'mapping2d');});
test('mission transformation moves area, execution route and launch reference together; bearing wraps',()=>{const m=source(),q=transformMission(m,10,20,10);assert.notEqual(q.points[0].lon,m.points[0].lon);assert.notEqual(q.rings[0][0].lat,m.rings[0][0].lat);assert.match(q.template!,/<wpml:direction>5<\/wpml:direction>/);assert.match(q.waylines!,/keep-me/);assert.match(q.waylines!,/takePhoto/);assert.notEqual(new DOMParser().parseFromString(q.template!,'text/xml').getElementsByTagName('wpml:startPositionRef')[0].textContent,'48.1,11.5,40');});
test('height offset keeps terrain variation and takeoff security height',()=>{const q=changeHeight(source(),5);assert.deepEqual(q.points.map(p=>p.height),[45,46]);assert.equal(q.height,30);assert.match(q.template!,/<wpml:takeOffSecurityHeight>40<\/wpml:takeOffSecurityHeight>/);});
test('speed and waypoint edits preserve original actions, indices and other points',async()=>{const m=changeSpeed(source(),3),q=editWaypoint(m,1,{lat:48.102,lon:11.504,height:52,speed:4});assert.equal(q.points[0].speed,3);assert.equal(q.points[0].lon,11.5);assert.equal(q.points[1].lon,11.504);assert.equal(q.points[1].height,52);assert.match(q.waylines!,/<wpml:actionGroupStartIndex>1<\/wpml:actionGroupStartIndex>/);assert.match(q.waylines!,/keep-me/);await exportMission(q);});
test('raster edit cannot export stale execution route',async()=>{const q=editMappingTemplate(source(),{direction:90,orthoCameraOverlapH:85,orthoCameraOverlapW:80,margin:2});assert.equal(q.waylines,null);assert.equal(q.points.length,0);const z=await JSZip.loadAsync(await exportMission(q));assert.equal(z.file('wpmz/waylines.wpml'),null);assert.match(await z.file('wpmz/template.kml')!.async('string'),/<wpml:direction>90<\/wpml:direction>/);});
test('KML template import wraps DJI XML for Pilot 2 recalculation; generic KML export refused',async()=>{const b=new TextEncoder().encode(template);const q=await readMission({name:'plan.kml',arrayBuffer:async()=>b.buffer});assert.equal(q.waylines,null);assert.equal(q.rings.length,1);await exportMission(q);const plain=inspectMission('plain.kml','<kml xmlns="http://www.opengis.net/kml/2.2"><Document><Placemark><Point><coordinates>11.5,48.1,0</coordinates></Point></Placemark></Document></kml>',null);await assert.rejects(()=>exportMission(plain),/no DJI/);});
test('invalid XML, coordinates, DTD and unsafe / empty missions refused',()=>{assert.throws(()=>inspectMission('bad.kml','<!DOCTYPE kml [<!ENTITY x SYSTEM "file:///etc/passwd">]><kml/>',null),/DTD/);assert.throws(()=>inspectMission('empty.kml','<kml><Document/></kml>',null),/No route/);assert.throws(()=>inspectMission('bad.kml',template.replace('11.5,48.1,0','181,48.1,0'),null),/Invalid WGS84/);assert.throws(()=>changeSpeed(source(),0));assert.throws(()=>editWaypoint(source(),0,{lat:91,lon:0,height:0,speed:1}));});

test('area editing preserves ring closure and removes stale execution route',async()=>{const q=editAreaVertex(source(),0,0,{lat:48.11,lon:11.51});assert.equal(q.waylines,null);assert.equal(q.rings[0][0].lat,48.11);assert.deepEqual(q.rings[0][0],q.rings[0][3]);await exportMission(q);});
test('archive keeps auxiliary KML resources after mission edits',async()=>{const z=new JSZip();z.file('wpmz/template.kml',template);z.file('wpmz/waylines.wpml',waylines);z.file('wpmz/res/auxiliary.kml','auxiliary resource');const b=await z.generateAsync({type:'uint8array'});const m=await readMission({name:'aux.kmz',arrayBuffer:async()=>b.slice().buffer});const out=await JSZip.loadAsync(await exportMission(changeHeight(m,1)));assert.equal(await out.file('wpmz/res/auxiliary.kml')!.async('string'),'auxiliary resource');});

test('insert / delete on a closed ring preserves closure, altitude, resources and original undo snapshot',async()=>{
 const original=source(),a=changeAreaTopology(original,0,'insert',2,{lat:48.1005,lon:11.5005});
 assert.equal(areaVertices(a.rings[0]).length,4);assert.equal(a.rings[0].length,5);assert.deepEqual(a.rings[0][0],a.rings[0][4]);assert.equal(a.waylines,null);assert.equal(original.waylines,waylines);assert.equal(areaVertices(original.rings[0]).length,3);
 const b=changeAreaTopology(a,0,'delete',0);assert.equal(areaVertices(b.rings[0]).length,3);assert.deepEqual(b.rings[0][0],b.rings[0][3]);assert.equal(b.rings[0][0].lon,11.501);
 const bytes=await exportMission(b),round=await readMission({name:'edited.kmz',arrayBuffer:async()=>bytes.slice().buffer as ArrayBuffer});assert.deepEqual(round.rings,b.rings);assert.throws(()=>changeAreaTopology(b,0,'delete',1),/at least three/);assert.throws(()=>changeAreaTopology(b,0,'insert',-1),/not found/);
});
test('open DJI rings expose each vertex once and allow insertions on the closing edge',()=>{
 const m=inspectMission('open.kmz',template.replace('11.501,48.101,0 11.5,48.1,0','11.501,48.101,0'),waylines);
 assert.equal(areaVertices(m.rings[0]).length,3);const q=changeAreaTopology(m,0,'insert',2);assert.equal(q.rings[0].length,4);assert.ok(Math.abs(q.rings[0][3].lat-48.1005)<1e-10);assert.ok(Math.abs(q.rings[0][3].lon-11.5005)<1e-10);
 const r=changeAreaTopology(q,0,'delete',3);assert.deepEqual(r.rings,m.rings);assert.throws(()=>changeAreaTopology(m,0,'insert',0,{lat:Infinity,lon:0}),/Invalid/);
});
