import {test} from 'node:test';import assert from 'node:assert/strict';import {DOMParser,XMLSerializer} from '@xmldom/xmldom';import JSZip from 'jszip';import {inspectMission,editAreaVertex,editMappingTemplate,exportMission,missionXml as X} from '../dji/mission';import {inferSettings,recalculateMission} from '../dji/planner';Object.assign(globalThis,{DOMParser,XMLSerializer});
const ns='http://www.dji.com/wpmz/1.0.6',head=`<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:wpml="${ns}"><Document>`;
const config='<wpml:missionConfig><wpml:takeOffSecurityHeight>40</wpml:takeOffSecurityHeight><wpml:droneInfo><wpml:droneEnumValue>77</wpml:droneEnumValue></wpml:droneInfo><wpml:payloadInfo><wpml:payloadEnumValue>66</wpml:payloadEnumValue><wpml:payloadPositionIndex>0</wpml:payloadPositionIndex></wpml:payloadInfo></wpml:missionConfig>';
const tpl=head+config+'<Folder><wpml:templateType>mapping2d</wpml:templateType><wpml:templateId>0</wpml:templateId><wpml:autoFlightSpeed>2</wpml:autoFlightSpeed><wpml:waylineCoordinateSysParam><wpml:heightMode>relativeToStartPoint</wpml:heightMode><wpml:globalShootHeight>25</wpml:globalShootHeight></wpml:waylineCoordinateSysParam><Placemark><wpml:height>40</wpml:height><wpml:gimbalPitchAngle>-90</wpml:gimbalPitchAngle><wpml:direction>0</wpml:direction><wpml:margin>0</wpml:margin><wpml:shootType>time</wpml:shootType><wpml:overlap><wpml:orthoCameraOverlapH>80</wpml:orthoCameraOverlapH><wpml:orthoCameraOverlapW>80</wpml:orthoCameraOverlapW></wpml:overlap><Polygon><outerBoundaryIs><LinearRing><coordinates>11.5,48,0 11.501,48,0 11.501,48.001,0 11.5,48.001,0</coordinates></LinearRing></outerBoundaryIs></Polygon></Placemark></Folder></Document></kml>';
const synthetic=()=>inspectMission('synthetic.kml',tpl,null);
test('template-only raster produces complete DJI WPML with contiguous indices and bounded action references',async()=>{const original=synthetic(),dirty=editAreaVertex(original,0,0,{lat:48,lon:11.4999}),q=recalculateMission(dirty,{laneSpacing:10,photoDistance:5});assert.ok(q.lanes>1);assert.ok(q.mission.points.length>2);assert.equal(q.mission.points[0].height,40);assert.ok(q.mission.points.every((p,i)=>p.index===i&&p.height===40&&p.speed===2));const d=X.xml(q.mission.waylines!);assert.equal(X.val(d,'executeHeightMode'),'relativeToStartPoint');assert.equal(X.val(d,'droneEnumValue'),'77');assert.equal(X.all(d,'startActionGroup').length,1);
 for(const g of X.all(d,'actionGroup')){assert.ok(X.numeric(g,'actionGroupStartIndex')!>=0);assert.ok(X.numeric(g,'actionGroupEndIndex')!<q.mission.points.length);assert.equal(X.val(g,'actionTriggerType'),'multipleTiming');assert.equal(X.numeric(g,'actionTriggerParam'),2.5);assert.equal(X.val(g,'actionActuatorFunc'),'takePhoto');}
 const z=await JSZip.loadAsync(await exportMission(q.mission));assert.ok(z.file('wpmz/template.kml'));assert.ok(z.file('wpmz/waylines.wpml'));assert.equal(original.waylines,null);
});
test('calibration survives boundary edits and overlap changes; action groups are regenerated for new route',()=>{const first=recalculateMission(synthetic(),{laneSpacing:5,photoDistance:4});const imported=inspectMission('import.kmz',tpl,first.mission.waylines);const inferred=inferSettings(imported);assert.ok(inferred);const dirty=editAreaVertex(imported,0,0,{lat:48.00001,lon:11.5});assert.deepEqual(inferSettings(dirty),inferred);const overlap=editMappingTemplate(dirty,{direction:45,orthoCameraOverlapH:90,orthoCameraOverlapW:90,margin:0}),newSettings=inferSettings(overlap)!;assert.ok(Math.abs(newSettings.laneSpacing-inferred.laneSpacing/2)<.01);assert.ok(Math.abs(newSettings.photoDistance-inferred.photoDistance/2)<.01);assert.ok(recalculateMission(overlap,newSettings).mission.points.length>0);
});
test('regeneration preserves startup focus / gimbal settings and remaps timelapse start and stop per lane',()=>{const seed=recalculateMission(synthetic(),{laneSpacing:10,photoDistance:5}),d=X.xml(seed.mission.waylines!);const p=X.all(d,'actionActuatorFunc')[1];p.textContent='startTimeLapse';const params=X.all(p.parentNode as Element,'actionActuatorFuncParam')[0];const n=d.createElementNS(ns,'wpml:minShootInterval');n.textContent='2.5';params.appendChild(n);const original=inspectMission('seed.kmz',tpl,new globalThis.XMLSerializer().serializeToString(d)),q=recalculateMission(original,{laneSpacing:8,photoDistance:6});const out=X.xml(q.mission.waylines!);assert.equal(new globalThis.XMLSerializer().serializeToString(X.all(out,'startActionGroup')[0]),new globalThis.XMLSerializer().serializeToString(X.all(X.xml(original.waylines!),'startActionGroup')[0]));assert.equal(X.all(out,'actionActuatorFunc').filter(e=>e.textContent==='startTimeLapse').length,q.lanes);assert.equal(X.all(out,'actionActuatorFunc').filter(e=>e.textContent==='stopTimeLapse').length,q.lanes);assert.ok(X.all(out,'minShootInterval').every(e=>Number(e.textContent)===3));});
test('unsupported terrain / mission types, custom waypoint actions and impossible photo intervals fail explicitly',()=>{assert.throws(()=>recalculateMission({...synthetic(),templateType:'mapping3d'},{laneSpacing:5,photoDistance:5}),/mapping2d/);assert.throws(()=>recalculateMission(synthetic(),{laneSpacing:5,photoDistance:.1}),/0.5/);const q=recalculateMission(synthetic(),{laneSpacing:5,photoDistance:5});const bad=inspectMission('bad.kmz',tpl,q.mission.waylines!.replace('takePhoto','hover'));assert.throws(()=>recalculateMission(bad,{laneSpacing:5,photoDistance:5}),/custom/);});
