import {test} from 'node:test';import assert from 'node:assert/strict';import {DOMParser,XMLSerializer} from '@xmldom/xmldom';import JSZip from 'jszip';import {inspectMission,editAreaVertex,editMappingTemplate,exportMission,readMission,setFlightHeight,setShootingHeight,setSubjectSurface,changeAreaTopology,changeSpeed,missionXml as X} from '../dji/mission';import {inferSettings,recalculateMission,estimateGsd,photoFootprint,recalculateTerrainMission,subjectDistance} from '../dji/planner';Object.assign(globalThis,{DOMParser,XMLSerializer});
const ns='http://www.dji.com/wpmz/1.0.6',head=`<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:wpml="${ns}"><Document>`;
const config='<wpml:missionConfig><wpml:takeOffSecurityHeight>40</wpml:takeOffSecurityHeight><wpml:droneInfo><wpml:droneEnumValue>77</wpml:droneEnumValue></wpml:droneInfo><wpml:payloadInfo><wpml:payloadEnumValue>66</wpml:payloadEnumValue><wpml:payloadPositionIndex>0</wpml:payloadPositionIndex></wpml:payloadInfo></wpml:missionConfig>';
const tpl=head+config+'<Folder><wpml:templateType>mapping2d</wpml:templateType><wpml:templateId>0</wpml:templateId><wpml:autoFlightSpeed>2</wpml:autoFlightSpeed><wpml:waylineCoordinateSysParam><wpml:heightMode>relativeToStartPoint</wpml:heightMode><wpml:globalShootHeight>25</wpml:globalShootHeight></wpml:waylineCoordinateSysParam><Placemark><wpml:height>40</wpml:height><wpml:gimbalPitchAngle>-90</wpml:gimbalPitchAngle><wpml:direction>0</wpml:direction><wpml:margin>0</wpml:margin><wpml:shootType>time</wpml:shootType><wpml:overlap><wpml:orthoCameraOverlapH>80</wpml:orthoCameraOverlapH><wpml:orthoCameraOverlapW>80</wpml:orthoCameraOverlapW></wpml:overlap><Polygon><outerBoundaryIs><LinearRing><coordinates>11.5,48,0 11.501,48,0 11.501,48.001,0 11.5,48.001,0</coordinates></LinearRing></outerBoundaryIs></Polygon></Placemark></Folder></Document></kml>';
const synthetic=()=>inspectMission('synthetic.kml',tpl,null);
test('template-only raster produces complete DJI WPML with contiguous indices and bounded action references',async()=>{const original=synthetic(),dirty=editAreaVertex(original,0,0,{lat:48,lon:11.4999}),q=recalculateMission(dirty,{laneSpacing:10,photoDistance:5});assert.ok(q.lanes>1);assert.ok(q.mission.points.length>2);assert.equal(q.mission.points[0].height,40);assert.ok(q.mission.points.every((p,i)=>p.index===i&&p.height===40&&p.speed===2));const d=X.xml(q.mission.waylines!);assert.equal(X.val(d,'executeHeightMode'),'relativeToStartPoint');assert.equal(X.val(d,'droneEnumValue'),'77');assert.equal(X.all(d,'startActionGroup').length,1);
 for(const g of X.all(d,'actionGroup')){assert.ok(X.numeric(g,'actionGroupStartIndex')!>=0);assert.ok(X.numeric(g,'actionGroupEndIndex')!<q.mission.points.length);assert.equal(X.val(g,'actionTriggerType'),'multipleTiming');assert.equal(X.numeric(g,'actionTriggerParam'),2.5);assert.equal(X.val(g,'actionActuatorFunc'),'takePhoto');}
 const z=await JSZip.loadAsync(await exportMission(q.mission));assert.ok(z.file('wpmz/template.kml'));assert.ok(z.file('wpmz/waylines.wpml'));assert.equal(original.waylines,null);
});
test('calibration survives boundary edits and overlap changes; action groups are regenerated for new route',()=>{const first=recalculateMission(synthetic(),{laneSpacing:5,photoDistance:4});const imported=inspectMission('import.kmz',tpl,first.mission.waylines);const inferred=inferSettings(imported);assert.ok(inferred);const dirty=editAreaVertex(imported,0,0,{lat:48.00001,lon:11.5});assert.deepEqual(inferSettings(dirty),inferred);const overlap=editMappingTemplate(dirty,{direction:45,orthoCameraOverlapH:90,orthoCameraOverlapW:90,margin:0}),newSettings=inferSettings(overlap)!;assert.ok(Math.abs(newSettings.laneSpacing-inferred.laneSpacing/2)<.01);assert.ok(Math.abs(newSettings.photoDistance-inferred.photoDistance/2)<.01);assert.ok(recalculateMission(overlap,newSettings).mission.points.length>0);
});
test('regeneration preserves startup focus / gimbal settings and remaps timelapse start and stop per lane',()=>{const seed=recalculateMission(synthetic(),{laneSpacing:10,photoDistance:5}),d=X.xml(seed.mission.waylines!);const p=X.all(d,'actionActuatorFunc')[1];p.textContent='startTimeLapse';const params=X.all(p.parentNode as Element,'actionActuatorFuncParam')[0];const n=d.createElementNS(ns,'wpml:minShootInterval');n.textContent='2.5';params.appendChild(n);const original=inspectMission('seed.kmz',tpl,new globalThis.XMLSerializer().serializeToString(d)),q=recalculateMission(original,{laneSpacing:8,photoDistance:6});const out=X.xml(q.mission.waylines!);assert.equal(new globalThis.XMLSerializer().serializeToString(X.all(out,'startActionGroup')[0]),new globalThis.XMLSerializer().serializeToString(X.all(X.xml(original.waylines!),'startActionGroup')[0]));assert.equal(X.all(out,'actionActuatorFunc').filter(e=>e.textContent==='startTimeLapse').length,q.lanes);assert.equal(X.all(out,'actionActuatorFunc').filter(e=>e.textContent==='stopTimeLapse').length,q.lanes);assert.ok(X.all(out,'minShootInterval').every(e=>Number(e.textContent)===3));});
test('unsupported terrain / mission types, custom waypoint actions and impossible photo intervals fail explicitly',()=>{assert.throws(()=>recalculateMission({...synthetic(),templateType:'mapping3d'},{laneSpacing:5,photoDistance:5}),/mapping2d/);assert.throws(()=>recalculateMission(synthetic(),{laneSpacing:5,photoDistance:.1}),/0.5/);const q=recalculateMission(synthetic(),{laneSpacing:5,photoDistance:5});const bad=inspectMission('bad.kmz',tpl,q.mission.waylines!.replace('takePhoto','hover'));assert.throws(()=>recalculateMission(bad,{laneSpacing:5,photoDistance:5}),/custom/);});

test('imported execution height wins over zero template and survives boundary edits, undo-independent topology edits and KMZ round trip',async()=>{
 const route=recalculateMission(synthetic(),{laneSpacing:5,photoDistance:4}).mission.waylines;
 const imported=inspectMission('zero.kmz',tpl.replace('<wpml:height>40','<wpml:height>0'),route);
 assert.equal(imported.flightHeight,40);assert.equal(imported.height,25);
 const moved=editAreaVertex(imported,0,0,{lat:48,lon:11.4999});assert.equal(moved.flightHeight,40);assert.equal(moved.height,25);assert.equal(X.numeric(X.xml(moved.template!),'height'),40);
 const changed=changeSpeed(changeAreaTopology(setFlightHeight(moved,55),0,'insert',0),2);
 assert.equal(changed.flightHeight,55);assert.equal(changed.height,40);
 const q=recalculateMission(changed,inferSettings(changed)!);assert.ok(q.mission.points.every(p=>p.height===55));
 const bytes=await exportMission(q.mission),round=await readMission({name:'round.kmz',arrayBuffer:async()=>bytes.slice().buffer as ArrayBuffer});assert.equal(round.flightHeight,55);assert.equal(round.height,40);
});
test('percentage density changes spacing, retains camera footprint and GSD; shooting height scales GSD',()=>{
 const seed=recalculateMission(synthetic(),{laneSpacing:5,photoDistance:4}),m=inspectMission('calibrated.kmz',tpl,seed.mission.waylines),before=inferSettings(m)!,g=estimateGsd(m,5280,3956)!;
 assert.ok(g.calibrated);assert.ok(g.x>0&&g.y>0);
 const more=editMappingTemplate(m,{direction:0,margin:0,orthoCameraOverlapW:90,orthoCameraOverlapH:90}),spacing=inferSettings(more)!;
 assert.ok(Math.abs(spacing.laneSpacing/before.laneSpacing-.5)<.001);assert.ok(Math.abs(spacing.photoDistance/before.photoDistance-.5)<.001);assert.deepEqual(estimateGsd(more,5280,3956),g);
 const higher=setFlightHeight(more,65),higherGsd=estimateGsd(higher,5280,3956)!;assert.ok(Math.abs(higherGsd.x/g.x-2)<.001);assert.ok(Math.abs(higherGsd.y/g.y-2)<.001);
 assert.equal(estimateGsd(m,0,3956),null);assert.equal(estimateGsd(m,NaN,3956),null);
 const dense=recalculateMission(more,spacing),sparse=recalculateMission(m,before);assert.ok(dense.lanes>sparse.lanes);assert.ok(dense.photoInterval<sparse.photoInterval);
});
test('M3E template has an optics-based estimate; unknown cameras require original route calibration',()=>{
 const footprint=photoFootprint(synthetic())!,gsd=estimateGsd(synthetic(),5280,3956)!;assert.equal(footprint.calibrated,false);assert.ok(gsd.x>.6&&gsd.x<.8);assert.ok(Math.abs(gsd.x-gsd.y)<.001);
 assert.equal(photoFootprint({...synthetic(),payload:'unknown'}),null);assert.equal(estimateGsd({...synthetic(),height:0},5280,3956),null);
});

test('terrain raster exports variable relative heights, remaps photo actions and retains shooting height / security height',async()=>{
 const options={model:{name:'synthetic DEM',crs:'EPSG:4326',width:200,height:200,sample:async(p:{lat:number;lon:number})=>500+(p.lat-48)*10000},start:{lat:48,lon:11.5},agl:30,launchOffset:2,step:5,maxVerticalSpeed:2};
 const q=await recalculateTerrainMission(synthetic(),{laneSpacing:10,photoDistance:5},options),t=q.terrain!;assert.ok(q.mission.points.length>100);assert.ok(Math.max(...t.heights)-Math.min(...t.heights)>5);assert.equal(q.mission.height,30);assert.equal(q.mission.heightMode,'relativeToStartPoint');assert.ok(q.mission.points.every((p,i)=>Math.abs(p.height-(options.agl-options.launchOffset+(p.lat-48)*10000))<.001));
 const d=X.xml(q.mission.waylines!);for(const g of X.all(d,'actionGroup')){const a=X.numeric(g,'actionGroupStartIndex')!,b=X.numeric(g,'actionGroupEndIndex')!;assert.ok(t.plan.legs.some(([s,e])=>s===a&&e===b));assert.ok(b<q.mission.points.length);}
 assert.ok(X.all(d,'waypointTurnMode').some(e=>e.textContent==='toPointAndPassWithContinuityCurvature'));assert.equal(X.numeric(d,'takeOffSecurityHeight'),40);
 const bytes=await exportMission(q.mission),round=await readMission({name:'terrain.kmz',arrayBuffer:async()=>bytes.slice().buffer as ArrayBuffer});assert.deepEqual(round.points.map(p=>p.height),q.mission.points.map(p=>p.height));
 await assert.rejects(recalculateTerrainMission({...synthetic(),heightMode:'WGS84'},{laneSpacing:10,photoDistance:5},options),/relative/);
 const next=await recalculateTerrainMission(editAreaVertex(round,0,0,{lat:48,lon:11.4999}),{laneSpacing:10,photoDistance:5},options);assert.ok(next.mission.points.length>0);
});

test('roof surface changes roof GSD and overlap spacing without changing flight height; launch offset is included once',async()=>{
 const seed=recalculateMission(synthetic(),{laneSpacing:5,photoDistance:4}),m=inspectMission('roof.kmz',tpl,seed.mission.waylines);
 assert.equal(subjectDistance(40,15,0),25);assert.equal(subjectDistance(40,15,2),27);assert.equal(subjectDistance(40,-5,0),45);
 const ground=setShootingHeight(m,40),roof=setSubjectSurface(m,20,0);assert.equal(roof.flightHeight,40);assert.equal(roof.height,20);assert.equal(roof.waylines,null);
 const groundGsd=estimateGsd(ground,5280,3956)!,roofGsd=estimateGsd(roof,5280,3956)!;assert.ok(Math.abs(roofGsd.x/groundGsd.x-.5)<.001);assert.ok(Math.abs(roofGsd.y/groundGsd.y-.5)<.001);
 const groundSpacing=inferSettings(ground)!,roofSpacing=inferSettings(roof)!;assert.ok(Math.abs(roofSpacing.laneSpacing/groundSpacing.laneSpacing-.5)<.001);assert.ok(Math.abs(roofSpacing.photoDistance/groundSpacing.photoDistance-.5)<.001);
 assert.equal(X.numeric(X.xml(roof.template!),'orthoCameraOverlapH'),80);assert.equal(X.numeric(X.xml(roof.template!),'orthoCameraOverlapW'),80);
 const rebuilt=recalculateMission(roof,roofSpacing);assert.ok(rebuilt.mission.points.every(p=>p.height===40));assert.equal(rebuilt.mission.height,20);
 const bytes=await exportMission(rebuilt.mission),round=await readMission({name:'roof.kmz',arrayBuffer:async()=>bytes.slice().buffer as ArrayBuffer});assert.equal(round.flightHeight,40);assert.equal(round.height,20);
 assert.equal(setSubjectSurface(m,15,2).height,27);assert.throws(()=>setSubjectSurface(m,40,0),/positive/);assert.throws(()=>setSubjectSurface(m,50,0),/positive/);assert.throws(()=>setSubjectSurface({...m,heightMode:'WGS84'},15,0),/relative/);assert.throws(()=>setSubjectSurface(m,15,-2),/valid/);assert.throws(()=>subjectDistance(40,NaN,0),/Invalid/);
});
