import React,{useRef,useState} from 'react';
import {Plane,Upload,Download,Undo2,RotateCcw,LocateFixed} from 'lucide-react';
import {usePreferences} from '../ui/preferences';
import {type Mission,transformMission,changeHeight,setFlightHeight,changeSpeed,editWaypoint,exportMission,mappingValue,editMappingTemplate,editAreaVertex,areaVertices,changeAreaTopology} from './mission';
import './dji.css';
import PlanningControls from './PlanningControls';
export default function DjiPanel({mission,onImport,onChange,onUndo,canUndo,onReset,onRemove,onFit,selected,onSelect,editing,onEditing,areaEditing,onAreaEditing}:{mission:Mission|null;onImport:(f:File)=>void;onChange:(m:Mission)=>void;onUndo:()=>void;canUndo:boolean;onReset:()=>void;onRemove:()=>void;onFit:()=>void;selected:number;onSelect:(i:number)=>void;editing:boolean;onEditing:(v:boolean)=>void;areaEditing:boolean;onAreaEditing:(v:boolean)=>void}){
 const {language}=usePreferences(),de=language==='de',s=(d:string,e:string)=>de?d:e;
 const input=useRef<HTMLInputElement>(null);const [error,setError]=useState(''),[busy,setBusy]=useState(false),[east,setEast]=useState('0'),[north,setNorth]=useState('0'),[angle,setAngle]=useState('0'),[delta,setDelta]=useState('0'),[speed,setSpeed]=useState('1.5');
 function apply(fn:()=>Mission){try{setError('');onChange(fn());}catch(e){setError(String(e instanceof Error?e.message:e));}}
 async function download(){if(!mission)return;setBusy(true);setError('');try{const bytes=await exportMission(mission),url=URL.createObjectURL(new Blob([bytes.slice().buffer as ArrayBuffer],{type:'application/vnd.google-earth.kmz'})),a=document.createElement('a');a.href=url;a.download=mission.name.replace(/\.(kml|kmz)$/i,'')+(mission.waylines?'-edited':'-template')+'.kmz';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}catch(e){setError(String(e instanceof Error?e.message:e));}finally{setBusy(false);}}
 const p=mission?.points[selected];
 return <details className="dji-panel" open><summary><Plane size={17}/><strong>DJI · Pilot 2</strong><span>{mission?mission.points.length+' WP':''}</span></summary><div className="dji-content">
  <input ref={input} type="file" accept=".kml,.kmz" hidden onChange={e=>{const f=e.target.files?.[0];if(f)onImport(f);e.target.value='';}}/>
  <button className="secondary-button full" onClick={()=>input.current?.click()}><Upload size={15}/>{s('Flugplan laden · KML / KMZ','Load flight plan · KML / KMZ')}</button>
  {!mission&&<p className="dji-note">{s('DJI-Missionen lokal anzeigen und bearbeiten. Flächen, Routen und Kameraaktionen bleiben gemeinsam im Export.','View and edit DJI missions locally. Survey areas, routes and camera actions are preserved together.')}</p>}
  {mission&&<>
   <strong className="dji-name" title={mission.name}>{mission.name}</strong><p className="dji-note">{mission.templateType} · {mission.points.length} {s('Wegpunkte','waypoints')} · {mission.rings.length} {s('Flächenringe','area rings')}<br/>WPML {mission.namespace.split('/').pop()||'—'} · {s('Drohne / Kamera-ID','Aircraft / camera ID')} {mission.drone||'—'} / {mission.payload||'—'}<br/>{s('Höhenbezug','Height reference')}: {mission.heightMode}</p>
   <div className="dji-actions"><button className="quiet-button" onClick={onFit}><LocateFixed size={14}/>{s('Flugplan zeigen','Show mission')}</button><button className="icon-button" aria-label={s('DJI-Änderung rückgängig','Undo DJI edit')} disabled={!canUndo} onClick={onUndo}><Undo2 size={16}/></button><button className="icon-button" aria-label={s('Originalflugplan wiederherstellen','Restore original mission')} onClick={onReset}><RotateCcw size={16}/></button></div>
   {!mission.namespace&&<p className="dji-warning">{s('Geometrie-KML: ohne DJI-Geräteparameter nur Vorschau und Bearbeitung. Für Pilot-2-Export einen originalen DJI-Flugplan laden.','Geometry KML: preview and editing only without DJI device settings. Load an original DJI mission for Pilot 2 export.')}</p>}
   {mission.flightHeight!==null&&<FlightHeight key={`${mission.name}:${mission.flightHeight}`} mission={mission} de={de} onApply={h=>apply(()=>setFlightHeight(mission,h))}/>}
   {mission.templateType==='mapping2d'&&<PlanningControls key={mission.name} mission={mission} onChange={onChange}/>}
   {!mission.waylines&&mission.namespace&&<p className="dji-warning">{s('Planungsvorlage ohne Route. Für 2D-Flächen oben „Route neu berechnen“ nutzen; alternativ in Pilot 2 berechnen.','Planning template without a route. For 2D areas use Recalculate route above; alternatively calculate in Pilot 2.')}</p>}
   <details><summary>{s('Mission verschieben / drehen','Move / rotate mission')}</summary><div className="dji-fields"><label>{s('Ost (m)','East (m)')}<input type="number" step="0.1" value={east} onChange={e=>setEast(e.target.value)}/></label><label>{s('Nord (m)','North (m)')}<input type="number" step="0.1" value={north} onChange={e=>setNorth(e.target.value)}/></label><label>{s('Drehung rechts (°)','Clockwise rotation (°)')}<input type="number" value={angle} onChange={e=>setAngle(e.target.value)}/></label></div><button className="secondary-button full" onClick={()=>apply(()=>transformMission(mission,Number(east),Number(north),Number(angle)))}>{s('Auf Fläche und Route anwenden','Apply to area and route')}</button><p className="dji-note">{s('Drehpunkt: Flächenmittelpunkt. Lokale metrische Verschiebung; Startreferenz und POI werden mitgeführt.','Pivot: area centroid. Local metric transform; start reference and POIs move with the mission.')}</p></details>
   <details><summary>{s('Höhe und Geschwindigkeit','Height and speed')}</summary><label className="dji-field">{s('Höhenversatz (m)','Height offset (m)')}<input type="number" value={delta} onChange={e=>setDelta(e.target.value)}/></label><button className="secondary-button full" onClick={()=>apply(()=>changeHeight(mission,Number(delta)))}>{s('Alle Flughöhen versetzen','Offset all flight heights')}</button><label className="dji-field">{s('Fluggeschwindigkeit (m/s)','Flight speed (m/s)')}<input type="number" min="0.1" max="15" step="0.1" value={speed} onChange={e=>setSpeed(e.target.value)}/></label><button className="secondary-button full" onClick={()=>apply(()=>changeSpeed(mission,Number(speed)))}>{s('Geschwindigkeit setzen','Set speed')}</button><p className="dji-note">{s('Höhenbezug und Geländeprofil bleiben erhalten. Zeitbasierte Fotointervalle bleiben unverändert: eine andere Geschwindigkeit verändert die Überlappung. Sicherheits-/Startflughöhe bleibt separat im Original.','Height reference and terrain profile remain intact. Timed photo intervals remain unchanged: changing speed changes overlap. Takeoff safety height remains separate in the original.')}</p></details>
   {!!mission.points.length&&<details><summary>{s('Wegpunkte bearbeiten','Edit waypoints')}</summary><label className="toggle-row"><span>{s('Auf Karte ziehen','Drag on map')}</span><input type="checkbox" checked={editing} onChange={e=>onEditing(e.target.checked)}/></label><label className="dji-field">{s('Wegpunkt','Waypoint')}<select value={selected} onChange={e=>onSelect(Number(e.target.value))}>{mission.points.map((q,i)=><option key={i} value={i}>{i+1} · {s('Route','Route')} {q.folder+1} / WP {q.index}</option>)}</select></label>{p&&<WaypointFields key={`${selected}:${p.lat}:${p.lon}:${p.height}:${p.speed}`} p={p} de={de} onApply={v=>apply(()=>editWaypoint(mission,selected,v))}/>}<p className="dji-note">{s('Wegpunktnummern und Kameraaktionen bleiben erhalten. Bei Flächenmissionen wird die ausführbare Route direkt bearbeitet; erneute Rasterberechnung in Pilot 2 kann diese Änderungen ersetzen.','Waypoint indices and camera actions are retained. For mapping missions the executable route is edited directly; recalculating the raster in Pilot 2 may replace these edits.')}</p></details>}
   {!!mission.rings.length&&<details><summary>{s('Flächenumriss bearbeiten','Edit survey boundary')}</summary><label className="toggle-row"><span>{s('Umriss auf Karte bearbeiten','Edit boundary on map')}</span><input type="checkbox" checked={areaEditing} onChange={e=>onAreaEditing(e.target.checked)}/></label><p className="dji-note">{s('Eckpunkte ziehen; + auf einer Kante klicken oder ziehen zum Einfügen. Eckpunkt anklicken zum Löschen. Mindestens drei Punkte bleiben erhalten.','Drag vertices; click or drag + on an edge to insert a point. Click a vertex to delete it. At least three points must remain.')}</p><AreaFields key={mission.template||''} mission={mission} de={de} onTopology={(r,i,op)=>apply(()=>changeAreaTopology(mission,r,op,i))} onApply={(r,i,p)=>apply(()=>editAreaVertex(mission,r,i,p))}/><p className="dji-warning">{s('Nach Umrissänderungen „Route neu berechnen“ nutzen. Rückgängig stellt die vorherige Route wieder her.','After boundary changes use Recalculate route. Undo restores the previous route.')}</p></details>}
   {mission.templateType.startsWith('mapping')&&<details><summary>{s('Flugraster / Überlappung','Flight raster / overlap')}</summary><MappingFields key={mission.template||''} mission={mission} de={de} onApply={v=>apply(()=>editMappingTemplate(mission,v))}/><p className="dji-warning">{s('Änderungen verwerfen das bisherige Raster. Anschließend „Route neu berechnen“ nutzen oder die Vorlage in Pilot 2 berechnen.','These changes discard the previous raster. Then use Recalculate route or calculate the template in Pilot 2.')}</p></details>}
   <button className="primary-button full" disabled={busy||!mission.namespace} onClick={()=>void download()}><Download size={16}/>{s(mission.waylines?'DJI-KMZ exportieren':'DJI-Vorlage exportieren',mission.waylines?'Export DJI KMZ':'Export DJI template')}</button>
   <p className="dji-note">{s('Vor dem Flug in Pilot 2 importieren und Route, Startpunkt, Höhenbezug und Aktionen prüfen. Der Export wurde strukturell geprüft; ein Test auf dem DJI-Controller steht noch aus.','Before flight, import into Pilot 2 and review route, start point, height reference and actions. Export is structurally validated; DJI controller testing is still pending.')}</p>
   <button className="quiet-button" onClick={onRemove}>{s('Flugplan entfernen','Remove flight plan')}</button>
  </>}{error&&<p role="alert" className="dji-warning">{error}</p>}
 </div></details>;
}
function WaypointFields({p,de,onApply}:{p:{lat:number;lon:number;height:number;speed:number};de:boolean;onApply:(p:{lat:number;lon:number;height:number;speed:number})=>void}){
 const [v,set]=useState(p);return <><div className="dji-fields">{(['lat','lon','height','speed'] as const).map(k=><label key={k}>{({lat:de?'Breite':'Latitude',lon:de?'Länge':'Longitude',height:de?'Höhe (m)':'Height (m)',speed:de?'Tempo (m/s)':'Speed (m/s)'})[k]}<input type="number" step="any" value={v[k]} onChange={e=>set({...v,[k]:Number(e.target.value)})}/></label>)}</div><button className="secondary-button full" onClick={()=>onApply(v)}>{de?'Wegpunkt übernehmen':'Apply waypoint'}</button></>;
}
function MappingFields({mission,de,onApply}:{mission:Mission;de:boolean;onApply:(v:{direction:number;orthoCameraOverlapH:number;orthoCameraOverlapW:number;margin:number})=>void}){
 const [v,set]=useState({direction:mappingValue(mission,'direction')??0,orthoCameraOverlapH:mappingValue(mission,'orthoCameraOverlapH')??80,orthoCameraOverlapW:mappingValue(mission,'orthoCameraOverlapW')??80,margin:mappingValue(mission,'margin')??0});
 return <><div className="dji-fields">{(Object.keys(v) as (keyof typeof v)[]).map(k=><label key={k}>{({direction:de?'Richtung (°)':'Direction (°)',orthoCameraOverlapH:de?'Längs (%)':'Forward (%)',orthoCameraOverlapW:de?'Quer (%)':'Side (%)',margin:de?'Rand (m)':'Margin (m)'})[k]}<input type="number" value={v[k]} onChange={e=>set({...v,[k]:Number(e.target.value)})}/></label>)}</div><button className="secondary-button full" onClick={()=>onApply(v)}>{de?'Vorlage übernehmen':'Apply template changes'}</button></>;
}

function AreaFields({mission,de,onApply,onTopology}:{mission:Mission;de:boolean;onApply:(ring:number,index:number,p:{lat:number;lon:number})=>void;onTopology:(ring:number,index:number,op:'insert'|'delete')=>void}){
 const [ring,setRing]=useState(0),[index,setIndex]=useState(0),[p,setP]=useState(mission.rings[0][0]);
 function choose(r:number,i:number){setRing(r);setIndex(i);setP(mission.rings[r][i]);}
 return <><label className="dji-field">{de?'Flächenring / Eckpunkt':'Area ring / vertex'}<select value={`${ring}:${index}`} onChange={e=>{const [r,i]=e.target.value.split(':').map(Number);choose(r,i);}}>{mission.rings.flatMap((r,ri)=>areaVertices(r).map((_,i)=><option key={`${ri}:${i}`} value={`${ri}:${i}`}>{ri+1} / {i+1}</option>))}</select></label><div className="dji-fields"><label>{de?'Breite':'Latitude'}<input type="number" step="any" value={p.lat} onChange={e=>setP({...p,lat:Number(e.target.value)})}/></label><label>{de?'Länge':'Longitude'}<input type="number" step="any" value={p.lon} onChange={e=>setP({...p,lon:Number(e.target.value)})}/></label></div><button className="secondary-button full" onClick={()=>onApply(ring,index,p)}>{de?'Umriss übernehmen':'Apply boundary changes'}</button><div className="dji-actions"><button className="quiet-button" onClick={()=>onTopology(ring,index,'insert')}>{de?'Punkt danach einfügen':'Insert point after'}</button><button className="quiet-button" disabled={areaVertices(mission.rings[ring]).length<=3} onClick={()=>onTopology(ring,index,'delete')}>{de?'Eckpunkt löschen':'Delete vertex'}</button></div></>;
}

function FlightHeight({mission,de,onApply}:{mission:Mission;de:boolean;onApply:(h:number)=>void}){
 const [value,setValue]=useState(String(mission.flightHeight)),heights=mission.points.map(p=>p.height),variable=heights.length>1&&Math.max(...heights)-Math.min(...heights)>.01;
 return <div><label className="dji-field">{variable?(de?'Flughöhe am ersten Wegpunkt (m)':'Flight height at first waypoint (m)'):(de?'Flughöhe (m)':'Flight height (m)')}<input type="number" step=".1" value={value} onChange={e=>setValue(e.target.value)}/></label><button className="secondary-button full" disabled={!value.trim()||!Number.isFinite(Number(value))} onClick={()=>onApply(Number(value))}>{de?'Flughöhe übernehmen':'Apply flight height'}</button><p className="dji-note">{mission.heightMode} · {de?'Aufnahmehöhe über dem Motiv':'Shooting height above subject'}: {mission.height??'—'} m{variable&&<><br/>{de?'Variable Höhenfolge: dieser Wert versetzt alle Wegpunkte. Für eine neue Geländeberechnung gelten die Einstellungen im DEM/DSM-Bereich.':'Variable height profile: this value offsets all waypoints. New terrain calculations use the DEM/DSM settings.'}</>}</p></div>;
}
