import React,{useState,useEffect,useRef} from 'react';
import {Route,Loader2} from 'lucide-react';
import {usePreferences} from '../ui/preferences';
import {type Mission,mappingValue,editMappingTemplate,setShootingHeight} from './mission';
import {inferSettings,recalculateMission,recalculateTerrainMission,photoFootprint,estimateGsd,type PlanResult} from './planner';
import TerrainControls,{LaunchHeightHelper} from './TerrainControls';
import type {TerrainOptions} from './terrain';
export default function PlanningControls({mission,onChange}:{mission:Mission;onChange:(m:Mission)=>void}){
 const [terrain,setTerrain]=useState<TerrainOptions|null>(null),[terrainEnabled,setTerrainEnabled]=useState(false);
 const current=useRef(mission),active=useRef(true),currentTerrain=useRef(terrain);current.current=mission;currentTerrain.current=terrain;
 useEffect(()=>{active.current=true;return()=>{active.current=false;};},[]);
 const planningMission=terrain&&mappingValue(mission,'globalShootHeight')!==null?setShootingHeight(mission,terrain.agl):mission;
 const {language}=usePreferences(),de=language==='de',s=(a:string,b:string)=>de?a:b,footprint=photoFootprint(planningMission),inferred=inferSettings(planningMission)||(footprint?{laneSpacing:footprint.width*(1-(mappingValue(mission,'orthoCameraOverlapW')??80)/100),photoDistance:footprint.length*(1-(mappingValue(mission,'orthoCameraOverlapH')??80)/100)}:null);
 const [manual,setManual]=useState(false),[lane,setLane]=useState('5'),[photo,setPhoto]=useState('5'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[last,setLast]=useState<PlanResult|null>(null);
 const [side,setSide]=useState(String(mappingValue(mission,'orthoCameraOverlapW')??80)),[forward,setForward]=useState(String(mappingValue(mission,'orthoCameraOverlapH')??80));
 const knownCamera=mission.drone==='77'&&mission.payload==='66', [pixelsX,setPixelsX]=useState(knownCamera?'5280':''),[pixelsY,setPixelsY]=useState(knownCamera?'3956':'');
 useEffect(()=>{setSide(String(mappingValue(mission,'orthoCameraOverlapW')??80));setForward(String(mappingValue(mission,'orthoCameraOverlapH')??80));},[mission.template]);
 const gsd=estimateGsd(planningMission,Number(pixelsX),Number(pixelsY));
 function applyOverlap(){try{if(!side.trim()||!forward.trim())throw new Error(s('Prozentwerte eingeben.','Enter percentage values.'));const next=editMappingTemplate(mission,{direction:mappingValue(mission,'direction')??0,margin:mappingValue(mission,'margin')??0,orthoCameraOverlapW:Number(side),orthoCameraOverlapH:Number(forward)});onChange(next);setManual(false);setError('');}catch(e){setError(String(e instanceof Error?e.message:e));}}
 const settings=inferred&&!manual?inferred:{laneSpacing:Number(lane),photoDistance:Number(photo)};
 function edit(key:'lane'|'photo',value:string){if(!manual&&inferred){setLane(String(inferred.laneSpacing));setPhoto(String(inferred.photoDistance));}setManual(true);if(key==='lane')setLane(value);else setPhoto(value);}
 async function calculate(){setBusy(true);setError('');try{await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));if(terrainEnabled&&!terrain)throw new Error(s('Geländeeinstellungen vervollständigen.','Complete terrain settings.'));const result=terrain?await recalculateTerrainMission(mission,settings,terrain):recalculateMission(mission,settings);if(!active.current)return;if(current.current!==mission||currentTerrain.current!==terrain)throw new Error(s('Planung während der Berechnung geändert. Bitte erneut berechnen.','Planning changed during calculation. Recalculate again.'));onChange(result.mission);setLast(result);}catch(e){setError(String(e instanceof Error?e.message:e));}finally{setBusy(false);}}
 return <section className="dji-planning"><strong>{s('Route neu berechnen','Recalculate route')}</strong><p className="dji-note">{s('2D-Flächenraster direkt auf diesem Gerät berechnen. Die neue Route erscheint sofort auf der Karte und wird als DJI-KMZ exportiert.','Calculate a 2D survey raster on this device. The new route appears immediately on the map and exports as DJI KMZ.')}</p>
 <div className="dji-fields"><label>{s('Querüberlappung (%)','Side overlap (%)')}<input type="number" min="0" max="95" step="1" value={side} onChange={e=>setSide(e.target.value)}/></label><label>{s('Fotodichte / Längsüberlappung (%)','Photo density / forward overlap (%)')}<input type="number" min="0" max="95" step="1" value={forward} onChange={e=>setForward(e.target.value)}/></label></div>
 <button className="secondary-button full" onClick={applyOverlap}>{s('Überlappung übernehmen','Apply overlap')}</button><p className="dji-note">{s('Mehr Längsüberlappung = mehr Fotos. Prozentwerte übernehmen, anschließend Route neu berechnen.','More forward overlap = more photos. Apply the percentages, then recalculate the route.')}</p>
 <div className="dji-fields"><label>{s('Fotobreite (Pixel)','Photo width (pixels)')}<input type="number" min="1" step="1" value={pixelsX} placeholder="5280" onChange={e=>setPixelsX(e.target.value)}/></label><label>{s('Fotohöhe (Pixel)','Photo height (pixels)')}<input type="number" min="1" step="1" value={pixelsY} placeholder="3956" onChange={e=>setPixelsY(e.target.value)}/></label></div>
 <p className="dji-note"><strong>GSD: {gsd?`≈ ${gsd.x.toFixed(2)} × ${gsd.y.toFixed(2)} cm/px`:s('nicht bestimmbar','unavailable')}</strong><br/>{knownCamera?'DJI Mavic 3 Enterprise · ':''}{s('Tatsächliche Fotoauflösung verwenden. Schätzung aus Originalraster oder Kamera-Bildwinkel und Aufnahmehöhe; bei geneigter Kamera / Gelände variiert die GSD im Bild.','Use the actual image resolution. Estimate from original raster or camera field of view and shooting height; tilted cameras / terrain produce varying GSD across the image.')}{!footprint&&' '+s('Ohne kalibriertes Originalraster oder unterstützte Kamera ist keine GSD verfügbar.','GSD requires a calibrated original raster or a supported camera.')}</p>
 <label className="toggle-row"><span>{s('Abstände automatisch ableiten','Derive spacing automatically')}</span><input type="checkbox" checked={!!inferred&&!manual} disabled={!inferred} onChange={e=>{if(!e.target.checked&&inferred){setLane(String(inferred.laneSpacing));setPhoto(String(inferred.photoDistance));}setManual(!e.target.checked);}}/></label>
 <div className="dji-fields"><label>{s('Bahnabstand (m)','Lane spacing (m)')}<input type="number" min=".25" step=".1" value={inferred&&!manual?Number(settings.laneSpacing.toFixed(3)):lane} onChange={e=>edit('lane',e.target.value)}/></label><label>{s('Fotoabstand (m)','Photo spacing (m)')}<input type="number" min=".1" step=".1" value={inferred&&!manual?Number(settings.photoDistance.toFixed(3)):photo} onChange={e=>edit('photo',e.target.value)}/></label></div>
 <p className="dji-note">{inferred&&footprint?.calibrated?s('Ableitung aus Originalraster und Fotoauslösern; geänderte Überlappung und Aufnahmehöhe werden berücksichtigt.','Derived from original lanes and capture actions; changed overlap and shooting height are taken into account.'):footprint?s('Ableitung aus M3E-Bildwinkel, Aufnahmehöhe und Überlappung.','Derived from M3E field of view, shooting height and overlap.'):s('Keine Kalibrierung aus der Originalroute verfügbar. Bahn- und Fotoabstand bitte passend zu Kamera, Aufnahmehöhe und gewünschter Überlappung setzen. Die Vorgabewerte sind keine Kamerakalibrierung.','No original-route calibration is available. Set lane and photo spacing for the camera, shooting height and desired overlap. Default values are not camera calibration.')}</p>
 <TerrainControls mission={mission} onChange={setTerrain} onEnabled={setTerrainEnabled}/><LaunchHeightHelper key={mission.name} mission={mission} onChange={onChange}/>
 <button className="primary-button full" disabled={busy||terrainEnabled&&!terrain||Number(side)!==mappingValue(mission,'orthoCameraOverlapW')||Number(forward)!==mappingValue(mission,'orthoCameraOverlapH')} onClick={()=>void calculate()}>{busy?<Loader2 size={16}/>:<Route size={16}/>} {s(busy?'Route wird berechnet …':'Route neu berechnen',busy?'Calculating route …':'Recalculate route')}</button>
 {last&&last.mission.waylines===mission.waylines&&<p role="status" className="dji-note">{s('Neu berechnet','Recalculated')}: {last.lanes} {s('Bahnen','lanes')} · {mission.points.length} WP · {Math.round(last.distance)} m · ~{Math.round(last.duration/60)} min · {last.photoInterval.toFixed(2)} s / {s('Foto','photo')}</p>}
 {last?.terrain&&last.mission.waylines===mission.waylines&&<TerrainChart terrain={last.terrain} de={de}/>}
 {error&&<p role="alert" className="dji-warning">{error}</p>}
 <p className="dji-note">{s('Neue Flughöhen und Fotoaktionen ersetzen die vorherige Route. Start-Kameraaktionen bleiben erhalten. Optionales lokales Höhenmodell, keine Hindernisprüfung und keine DJI-Rastergarantie; vor dem Flug in Pilot 2 prüfen.','New flight heights and capture actions replace the prior route. Initial camera actions are retained. Optional local elevation model, no obstacle checking or identical DJI raster guarantee; review in Pilot 2 before flying.')}</p>
 </section>;
}

function TerrainChart({terrain,de}:{terrain:NonNullable<PlanResult['terrain']>;de:boolean}){
 const {heights,plan,agl,startElevation,launchOffset}=terrain,min=Math.min(...heights),max=Math.max(...heights),span=Math.max(1,max-min),f=heights.map((h,i)=>`${10+i/(heights.length-1)*280},${85-(h-min)/span*65}`).join(' ');
 return <div className="dji-note"><strong>{de?'Höhenprofil relativ zum Start':'Height profile relative to launch'}: {min.toFixed(1)}–{max.toFixed(1)} m</strong><svg viewBox="0 0 300 105" role="img" aria-label={de?'Relative Wegpunkthöhen entlang der Route':'Relative waypoint heights along route'} style={{width:'100%',height:'auto'}}><line x1="10" x2="290" y1="85" y2="85" stroke="currentColor" opacity=".3"/><polyline points={f} fill="none" stroke="var(--s-mint)" strokeWidth="2"/><text x="10" y="102" fill="currentColor" fontSize="9">0</text><text x="235" y="102" fill="currentColor" fontSize="9">{plan.points.length} WP</text></svg><p>{de?'Modellabstand':'Model clearance'}: {agl} m · {de?'Modellhöhe am Start':'Launch model elevation'}: {startElevation.toFixed(2)} m · {de?'Startversatz':'Launch offset'}: {launchOffset} m</p></div>;
}
