import React,{useState,useEffect} from 'react';
import {usePreferences} from '../ui/preferences';
import {type Mission,mappingValue,setShootingHeight,setSubjectSurface} from './mission';
import {estimateGsd,subjectDistance} from './planner';
export default function SurfaceControls({mission,widthPixels,heightPixels,terrainEnabled,onChange}:{mission:Mission;widthPixels:number;heightPixels:number;terrainEnabled:boolean;onChange:(m:Mission)=>void}){
 const {language}=usePreferences(),de=language==='de',s=(a:string,b:string)=>de?a:b;
 const [roof,setRoof]=useState(String((mission.flightHeight??0)-(mission.height??0))),[launch,setLaunch]=useState('0'),[error,setError]=useState('');
 const variable=mission.points.length>1&&Math.max(...mission.points.map(p=>p.height))-Math.min(...mission.points.map(p=>p.height))>.01;
 const supported=mappingValue(mission,'globalShootHeight')!==null&&mission.heightMode==='relativeToStartPoint'&&!variable&&!terrainEnabled;
 useEffect(()=>{if(supported)setRoof(String((mission.flightHeight??0)+Number(launch)-(mission.height??0)));},[mission.flightHeight,mission.height]);
 const valid=[roof,launch].every(v=>v.trim()&&Number.isFinite(Number(v)))&&Number(launch)>=0&&mission.flightHeight!==null;
 const distance=valid?subjectDistance(mission.flightHeight!,Number(roof),Number(launch)):null,groundDistance=valid?mission.flightHeight!+Number(launch):null;
 function gsd(h:number|null){return h!==null&&h>0?estimateGsd(setShootingHeight(mission,h),widthPixels,heightPixels):null;}
 const target=supported&&distance!==null&&distance>0?gsd(distance):null,ground=supported?gsd(groundDistance):null;
 const display=(g:ReturnType<typeof estimateGsd>)=>g?`≈ ${g.x.toFixed(2)} × ${g.y.toFixed(2)} cm/px`:'—';
 return <details open><summary>{s('Dach / Motivebene und GSD','Roof / subject surface and GSD')}</summary><div className="dji-fields"><label>{s('Dach / Motiv über Startboden (m)','Roof / subject above launch ground (m)')}<input type="number" disabled={!supported} step=".1" value={roof} onChange={e=>setRoof(e.target.value)}/></label><label>{s('Start über Startboden (m)','Launch above launch ground (m)')}<input type="number" disabled={!supported} min="0" step=".1" value={launch} onChange={e=>setLaunch(e.target.value)}/></label></div>
 <p className="dji-note">{s('Aufnahmeabstand zum Dach / Motiv','Capture distance above roof / subject')}: <strong>{supported&&distance!==null?`${distance.toFixed(2)} m`:'—'}</strong><br/><strong>{s('GSD auf Dach / Motiv','GSD on roof / subject')}: {display(target)}</strong><br/>{s('GSD auf Startbodenniveau','GSD at launch ground level')}: {display(ground)}</p>
 <p className="dji-note">{s('Abstand = relative Flughöhe + Startversatz − Dach-/Motivhöhe. Beispiel: 40 m Flughöhe, 15 m Dach, Start am Boden → 25 m Aufnahmeabstand. Bei gleichbleibender Flughöhe werden die Bahn- und Fotoabstände für dieselben Überlappungsprozente kleiner; die GSD auf dem Dach wird feiner. Beim Import wird die Motivebene aus Flug- und Aufnahmehöhe mit zunächst 0 m Startversatz abgeleitet; Dachhöhe und Startversatz prüfen.','Distance = relative flight height + launch offset − roof / subject height. Example: 40 m flight height, 15 m roof, ground launch → 25 m capture distance. At unchanged flight height, lane and photo spacing for the same overlap percentages become smaller; roof GSD becomes finer. On import the subject level is inferred from flight and shooting height with an initial zero launch offset; verify roof height and launch offset.')}</p>
 <button className="secondary-button full" disabled={!supported||distance===null||distance<=0} onClick={()=>{try{onChange(setSubjectSurface(mission,Number(roof),Number(launch)));setError('');}catch(e){setError(String(e instanceof Error?e.message:e));}}}>{s('Motivebene übernehmen','Apply subject surface')}</button>
 <p className="dji-note">{s('Übernehmen erhält die Flughöhe, setzt den Motivabstand und aktiviert automatische Bahn-/Fotoabstände. Danach „Route neu berechnen“. Die Prozentwerte bleiben bestehen. Schätzung für eine horizontale Ebene; geneigte Dächer/Kameras haben örtlich unterschiedliche GSD.','Apply preserves flight height, sets subject clearance and enables automatic lane/photo spacing. Then Recalculate route. Percentages are retained. Estimate for a horizontal plane; sloping roofs / cameras have spatially varying GSD.')}</p>
 {!supported&&<p className="dji-warning">{s('Feste Motivebene nur bei konstanter Flughöhe relativ zum Start. Bei DEM/DSM-Geländefolge gilt der dort eingestellte Modellabstand; Dächer sind in einem DSM bereits enthalten und dürfen nicht noch einmal abgezogen werden.','A fixed subject surface requires constant height relative to launch. DEM/DSM terrain following uses the configured model clearance; roofs already included in a DSM must not be subtracted again.')}</p>}
 {supported&&distance!==null&&distance<=0&&<p role="alert" className="dji-warning">{s('Die Flughöhe muss oberhalb der Dach-/Motivebene liegen.','Flight height must be above the roof / subject surface.')}</p>}{error&&<p role="alert" className="dji-warning">{error}</p>}
 </details>;
}
