import React,{useEffect,useState} from 'react';
import {usePreferences} from '../ui/preferences';
import {type Mission,missionXml as X,setFlightHeight,setShootingHeight} from './mission';
import {readElevationModel,relativeHeight,type ElevationModel,type TerrainOptions} from './terrain';
export default function TerrainControls({mission,onChange,onEnabled}:{mission:Mission;onChange:(v:TerrainOptions|null)=>void;onEnabled:(v:boolean)=>void}){
 const {language}=usePreferences(),de=language==='de',s=(a:string,b:string)=>de?a:b;
 const raw=mission.template?X.val(X.xml(mission.template),'startPositionRef').split(','):[];
 const [enabled,setEnabled]=useState(false),[model,setModel]=useState<ElevationModel|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[metres,setMetres]=useState(false);
 const [lat,setLat]=useState(raw.length===3?raw[0]:''),[lon,setLon]=useState(raw.length===3?raw[1]:''),[agl,setAgl]=useState(String(mission.height??30)),[offset,setOffset]=useState('0'),[step,setStep]=useState('5'),[vertical,setVertical]=useState('2');
 useEffect(()=>{if(!enabled)setAgl(String(mission.height??30));},[mission.height,enabled]);
 const valid=metres&&!!lat.trim()&&!!lon.trim()&&!!agl.trim()&&!!offset.trim()&&!!step.trim()&&!!vertical.trim()&&[lat,lon,agl,offset,step,vertical].every(v=>Number.isFinite(Number(v)))&&Math.abs(Number(lat))<=85&&Math.abs(Number(lon))<=180&&Number(agl)>0&&Number(offset)>=0&&Number(step)>=1&&Number(step)<=50&&Number(vertical)>0&&Number(vertical)<=5;
 useEffect(()=>{onEnabled(enabled);onChange(enabled&&model&&valid?{model,start:{lat:Number(lat),lon:Number(lon)},agl:Number(agl),launchOffset:Number(offset),step:Number(step),maxVerticalSpeed:Number(vertical)}:null);},[enabled,model,valid,lat,lon,agl,offset,step,vertical,onChange,onEnabled]);
 async function load(file:File){setLoading(true);setError('');setModel(null);setMetres(false);try{setModel(await readElevationModel(file));}catch(e){setError(String(e instanceof Error?e.message:e));}finally{setLoading(false);}}
 return <details><summary>{s('Geländefolge · lokales DEM / DSM','Terrain following · local DEM / DSM')}</summary><label className="toggle-row"><span>{s('Höhenmodell verwenden','Use elevation model')}</span><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/></label>
 <label className="dji-field">{s('Höhenmodell laden · GeoTIFF','Load elevation model · GeoTIFF')}<input type="file" accept=".tif,.tiff" disabled={loading} onChange={e=>{const file=e.target.files?.[0];if(file)void load(file);e.target.value='';}}/></label>
 {loading&&<p className="dji-note">{s('Höhenmodell wird geöffnet …','Opening elevation model …')}</p>}{model&&<><p className="dji-note">{model.name} · {model.crs} · {model.width} × {model.height}</p><button className="quiet-button" onClick={()=>{setModel(null);setMetres(false);}}>{s('Höhenmodell entfernen','Remove elevation model')}</button></>}
 <label className="toggle-row"><span>{s('Rasterwerte sind Höhen in Metern','Raster values are elevations in metres')}</span><input type="checkbox" checked={metres} onChange={e=>setMetres(e.target.checked)}/></label>
 <div className="dji-fields"><label>{s('Startpunkt · Breite','Launch point · latitude')}<input type="number" step="any" value={lat} onChange={e=>setLat(e.target.value)}/></label><label>{s('Startpunkt · Länge','Launch point · longitude')}<input type="number" step="any" value={lon} onChange={e=>setLon(e.target.value)}/></label><label>{s('Abstand über Modell (m)','Clearance above model (m)')}<input type="number" min=".1" step=".1" value={agl} onChange={e=>setAgl(e.target.value)}/></label><label>{s('Start über Modell (m)','Launch above model (m)')}<input type="number" min="0" step=".1" value={offset} onChange={e=>setOffset(e.target.value)}/></label><label>{s('Abtastabstand (m)','Sampling step (m)')}<input type="number" min="1" max="50" step="1" value={step} onChange={e=>setStep(e.target.value)}/></label><label>{s('Max. Steigen / Sinken (m/s)','Max. climb / descent (m/s)')}<input type="number" min=".1" max="5" step=".1" value={vertical} onChange={e=>setVertical(e.target.value)}/></label></div>
 <p className="dji-note">{s('DEM/DTM folgt dem Boden; DSM folgt auch Dächern und Vegetation. Ein RGB-Orthofoto enthält keine Geländehöhen. Startpunkt und gesamte Route müssen im selben Modell liegen. Bei Handstart vom Boden: z. B. 2 m Start über Modell; bei DSM-Dachstart zählt das Dach bereits zum Modell.','DEM/DTM follows bare ground; DSM also follows roofs and vegetation. An RGB orthophoto contains no terrain elevations. The start and complete route must be covered by the same model. For a hand launch from ground: e.g. 2 m above the model; for a roof launch with a DSM, the roof is already part of the model.')}</p>
 <p className="dji-note">{s('Relative Höhe = Modellhöhe an der Route − Modellhöhe am Start + gewünschter Abstand − Startversatz. Der Startpunkt muss der tatsächlichen Startreferenz im Controller entsprechen. Nach Änderungen „Route neu berechnen“. Höhen werden vorab berechnet, entlang der Bahnen und Verbindungen verdichtet und in die KMZ geschrieben. Das ist keine Echtzeit-Sensorregelung. Pilot-2-Neuberechnung würde die Höhenfolge ersetzen.','Relative height = model elevation along route − model elevation at launch + desired clearance − launch offset. The launch point must match the actual launch reference in the controller. After edits use Recalculate route. Heights are precomputed, sampled along lanes and transfers, and written into the KMZ. This is not live sensor control. Pilot 2 recalculation would replace this height profile.')}</p>
 {enabled&&(!model||!valid)&&<p className="dji-warning">{s('Höhenmodell laden, Meter bestätigen und gültige Start-/Höhenwerte eingeben, um die Route zu berechnen.','Load an elevation model, confirm metres, and enter valid launch/height values to calculate the route.')}</p>}
 <p className="dji-note">{s('Nur relative Startpunkt-Missionen. NoData, fehlende Modellabdeckung und zu starke Steigungen stoppen die Berechnung. Abtastung und Modellauflösung begrenzen die Genauigkeit; keine Hindernisprüfung zwischen Stützpunkten. Höhenprofil, Startreferenz und Start/Rückkehr separat in Pilot 2 prüfen.','Relative-to-launch missions only. NoData, missing model coverage and excessive slopes stop calculation. Sampling and model resolution limit accuracy; obstacles between samples are not checked. Review the height profile, launch reference, takeoff and return separately in Pilot 2.')}</p>
 {error&&<p role="alert" className="dji-warning">{error}</p>}
 </details>;
}
export function LaunchHeightHelper({mission,onChange}:{mission:Mission;onChange:(m:Mission)=>void}){
 const {language}=usePreferences(),de=language==='de',s=(a:string,b:string)=>de?a:b;
 const [clearance,setClearance]=useState(String(mission.height??30)),[difference,setDifference]=useState('0'),[offset,setOffset]=useState('2'),[error,setError]=useState('');
 const valid=[clearance,difference,offset].every(v=>v.trim()&&Number.isFinite(Number(v)))&&Number(clearance)>0&&Number(offset)>=0;
 const relative=valid?relativeHeight(Number(difference),0,Number(clearance),Number(offset)):null;
 return <details><summary>{s('Rechenhilfe · Handstart / erhöhter Start','Calculator · hand launch / elevated launch')}</summary><div className="dji-fields"><label>{s('Gewünschter Boden-/Motivabstand (m)','Desired ground / subject clearance (m)')}<input type="number" min=".1" step=".1" value={clearance} onChange={e=>setClearance(e.target.value)}/></label><label>{s('Motivniveau gegenüber Startboden (m)','Subject level relative to launch ground (m)')}<input type="number" step=".1" value={difference} onChange={e=>setDifference(e.target.value)}/></label><label>{s('Start über Startboden (m)','Launch above launch ground (m)')}<input type="number" min="0" step=".1" value={offset} onChange={e=>setOffset(e.target.value)}/></label></div>
 <p className="dji-note"><strong>{s('Einzustellende relative Flughöhe','Required relative flight height')}: {relative===null?'—':relative.toFixed(2)} m</strong><br/>{s('Beispiel: 30 m Bodenabstand, gleiches Bodenniveau, Start 2 m über Boden → 28 m relativ zum Start. Unverändert 30 m relativ ergeben etwa 32 m über Boden; der Startversatz wird abgezogen, nicht addiert. Bei 10 m höherem Motivniveau wären 38 m relativ nötig.','Example: 30 m ground clearance, level ground, launch 2 m above ground → 28 m relative to launch. An unchanged 30 m relative means approximately 32 m above ground; subtract the launch offset rather than adding it. A subject 10 m higher requires 38 m relative.')}</p>
 <p className="dji-note">{s('Gilt, wenn DJI die tatsächliche Startposition als Höhennull verwendet. Die im Controller verwendete Referenz prüfen; Motorstart, Startpunkt und Höhenreferenz können vom Arbeitsablauf abhängen. Danach die Route für passende Fotoabstände neu berechnen. Die Rechenhilfe setzt eine feste Motivebene voraus; für wechselndes Gelände das Höhenmodell nutzen. Sicherheits-/Start- und RTH-Höhe werden nicht verändert.','Applies when DJI uses the actual launch position as height zero. Check the reference used by the controller; motor start, launch point and height reference can depend on the workflow. Then recalculate the route for matching photo spacing. The calculator assumes a fixed subject plane; use the elevation model for varying terrain. Takeoff safety and RTH heights are not changed.')}</p>
 <button className="secondary-button full" disabled={relative===null||mission.heightMode!=='relativeToStartPoint'} onClick={()=>{try{onChange(setShootingHeight(setFlightHeight(mission,relative!),Number(clearance)));setError('');}catch(e){setError(String(e instanceof Error?e.message:e));}}}>{s('Berechnete Flughöhe übernehmen','Apply calculated flight height')}</button>{error&&<p role="alert" className="dji-warning">{error}</p>}
 </details>;
}
